// <auto-generated>
// 此文件由 WSFrame 自动生成。
// 该文件用于维护 UI 组件字段、组件引用和 InitComponent 事件绑定。
// 该文件可能会在下次生成时被整体覆盖，请不要在此文件中手写业务逻辑。
// 如需扩展功能，请在对应 WindowCode 或同名 partial 类的非生成文件中编写。
// </auto-generated>
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace WS_Modules.UIModule
{
    /// <summary>
    /// DialogueWindow 的生成绑定数据，保存对白控件、Choice 根节点和行资源配置。
    /// </summary>
	public class DialogueWindowDataComponent : MonoBehaviour
	{
		//窗口配置
		public bool IsFullWindow;
		public bool DoAnimation = true;

		//自定义字段
		public Button AdvanceButton;

		public TMP_Text SpeakerNameTMP_Text;

		public TMP_Text SpeakContentTMP_Text;

		// 与 SpeakContentTMP_Text 同一对象上的文字表现组件，由窗口组合根显式注入 SpeechView。
		public TMProTypeWriter SpeakContentTypeWriter;

		public Transform DialogueChoiceRootTransform;

		[WSAddressableKey]
		public string OptionPrefabPath = "OptionChoice";

		public int InitialChoiceRowCount = 3;

		/// <summary>由生成代码在窗口初始化阶段绑定本组件对应的 Window。</summary>
		/// <param name="target">承载本组件的 DialogueWindow。</param>
		public void InitComponent(WindowBase target)
		{
		     //组件事件绑定
		     DialogueWindow mWindow=(DialogueWindow)target;
		}
	}
}
