#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using WS_Modules.GAS.TAG;

namespace WS_Modules.GAS.Editor
{
    /// <summary>生成可由业务代码直接引用的 Gameplay Tag 常量。</summary>
    public static class RuntimeGameplayTagGenerator
    {
        /// <summary>生成文件所在目录。</summary>
        public const string RootPath = "Assets/GAS_Light/TagSystem/Generated";
        /// <summary>生成文件资产路径。</summary>
        public const string GeneratedAssetPath = RootPath + "/GameplayTags.Generated.cs";

        /// <summary>根据规范路径创建确定性的合法 C# 标识符。</summary>
        public static string CreateIdentifier(string path)
        {
            if (string.IsNullOrEmpty(path)) return "Empty";
            var builder = new StringBuilder(path.Length + 5);
            builder.Append("Tag_");
            for (int i = 0; i < path.Length; i++)
            {
                char c = path[i];
                if (char.IsLetterOrDigit(c) || c == '_') builder.Append(c); else builder.Append('_');
            }
            if (builder.Length == 4 || char.IsDigit(builder[4])) builder.Insert(4, '_');
            return builder.ToString();
        }

        /// <summary>生成完整 C# 源码，但不写入磁盘。</summary>
        public static string GenerateSource(IReadOnlyDictionary<string, GameplayTag> paths)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using WS_Modules.GAS.TAG;");
            builder.AppendLine();
            builder.AppendLine("namespace WS_Modules.GAS.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>由 Gameplay Tag 烘焙器生成的稳定标签常量。</summary>");
            builder.AppendLine("    public static class GameplayTags");
            builder.AppendLine("    {");
            foreach (KeyValuePair<string, GameplayTag> pair in paths.OrderBy(item => item.Key, StringComparer.Ordinal))
            {
                builder.AppendLine($"        /// <summary>{EscapeXml(pair.Key)}</summary>");
                builder.AppendLine($"        public static readonly GameplayTag {CreateIdentifier(pair.Key)} = new GameplayTag({pair.Value.Id});");
            }
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        /// <summary>通过同目录临时文件原子替换生成源码。</summary>
        public static void WriteAtomically(string source)
        {
            Directory.CreateDirectory(RootPath);
            string tempPath = GeneratedAssetPath + ".tmp";
            File.WriteAllText(tempPath, source, new UTF8Encoding(false));
            if (File.Exists(GeneratedAssetPath)) File.Replace(tempPath, GeneratedAssetPath, null);
            else File.Move(tempPath, GeneratedAssetPath);
        }

        // 防止路径中的特殊字符破坏生成的 XML 文档注释。
        private static string EscapeXml(string value) => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
#endif
