#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using WS_Modules.GAS.AttributeSystem;

namespace WS_Modules.GAS.Editor
{
    /// <summary>生成可由业务代码直接引用的全局 Gameplay Attribute 常量。</summary>
    public static class RuntimeGameplayAttributeGenerator
    {
        #region 常量

        /// <summary>生成文件所在目录。</summary>
        public const string RootPath = "Assets/GAS_Light/AttributeSystem/Generated";

        /// <summary>生成 C# 文件的资源路径。</summary>
        public const string GeneratedAssetPath = RootPath + "/GameplayAttributes.Generated.cs";

        #endregion

        #region 生成

        /// <summary>把作者名称转换为确定且合法的 C# 标识符。</summary>
        /// <param name="name">Attribute 作者名称。</param>
        /// <returns>带 Attribute_ 前缀的合法标识符。</returns>
        public static string CreateIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name)) return "Attribute_Empty";
            var builder = new StringBuilder(name.Length + 10);
            builder.Append("Attribute_");
            for (int i = 0; i < name.Length; i++)
            {
                char character = name[i];
                builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
            }

            if (char.IsDigit(builder[10])) builder.Insert(10, '_');
            return builder.ToString();
        }

        /// <summary>生成完整 C# 源码，但不写入磁盘。</summary>
        /// <param name="attributes">名称到稳定 Attribute 的映射。</param>
        /// <returns>确定排序的 C# 源码。</returns>
        public static string GenerateSource(
            IReadOnlyDictionary<string, GameplayAttribute> attributes)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("using WS_Modules.GAS.AttributeSystem;");
            builder.AppendLine();
            builder.AppendLine("namespace WS_Modules.GAS.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>由 Attribute Spec Bake 生成的稳定访问常量。</summary>");
            builder.AppendLine("    public static class GameplayAttributes");
            builder.AppendLine("    {");
            foreach (KeyValuePair<string, GameplayAttribute> pair in
                     attributes.OrderBy(item => item.Key, StringComparer.Ordinal))
            {
                builder.AppendLine($"        /// <summary>{EscapeXml(pair.Key)}</summary>");
                builder.AppendLine(
                    $"        public static readonly GameplayAttribute {CreateIdentifier(pair.Key)} = " +
                    $"new GameplayAttribute({pair.Value.Id}, \"{EscapeCSharp(pair.Value.Name)}\");");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        /// <summary>通过同目录临时文件原子替换生成源码。</summary>
        /// <param name="source">完整 C# 源码。</param>
        public static void WriteAtomically(string source)
        {
            Directory.CreateDirectory(RootPath);
            string temporaryPath = GeneratedAssetPath + ".tmp";
            File.WriteAllText(temporaryPath, source, new UTF8Encoding(false));
            if (File.Exists(GeneratedAssetPath))
                File.Replace(temporaryPath, GeneratedAssetPath, null);
            else
                File.Move(temporaryPath, GeneratedAssetPath);
        }

        // 防止作者名称破坏生成的 XML 文档注释。
        private static string EscapeXml(string value) =>
            value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

        /// <summary>转义生成常量中会破坏 C# 字符串的字符。</summary>
        /// <param name="value">待转义名称。</param>
        /// <returns>可直接写入 C# 字符串字面量的文本。</returns>
        private static string EscapeCSharp(string value) =>
            (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");

        #endregion
    }
}
#endif
