using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace WS_Modules.UIModule.Editor
{
    /// <summary>
    /// 扫描 Assets 中的 UXML 和 USS 文件，并生成对应的静态路径常量。
    /// </summary>
    public static class UxmlUssPathGenerator
    {
        #region 常量与字段

        private const string AssetRoot = "Assets";
        private const string GeneratedFilePath =
            "Assets/Scripts/WSFrame/Utilities/Editor/UXMLUSSGenerate/UxmlUssPathConstants.generated.cs";
        #endregion

        #region 公开操作

        /// <summary>
        /// 扫描 Assets 中的 UXML 和 USS 资源，并刷新生成的路径常量文件。
        /// </summary>
        [MenuItem("Tools/WSFrame/UI/Generate UXML USS Paths", priority = 2000)]
        public static void Generate()
        {
            List<ResourceEntry> entries = FindResourceEntries();
            string source = BuildGeneratedSource(entries);

            // 生成文件只在内容发生变化时写入，避免无意义地触发 Unity 的脚本重新导入。
            if (!File.Exists(GeneratedFilePath) || File.ReadAllText(GeneratedFilePath) != source)
            {
                File.WriteAllText(GeneratedFilePath, source, new UTF8Encoding(false));
            }

            AssetDatabase.Refresh();
            Debug.Log($"Generated UXML/USS path constants. UXML: {entries.Count(entry => entry.Kind == ResourceKind.Uxml)}, USS: {entries.Count(entry => entry.Kind == ResourceKind.Uss)}.");
        }

        #endregion

        #region 资源扫描

        /// <summary>
        /// 查找 Assets 下所有支持的资源，并按扩展名及路径稳定排序。
        /// </summary>
        /// <returns>待生成常量的资源条目。</returns>
        private static List<ResourceEntry> FindResourceEntries()
        {
            // UXML/USS 在 Unity 中分别导入为 VisualTreeAsset/StyleSheet，按资源类型查询可避免遗漏导入器生成的资源。
            IEnumerable<string> guids = AssetDatabase.FindAssets("t:VisualTreeAsset", new[] { AssetRoot })
                .Concat(AssetDatabase.FindAssets("t:StyleSheet", new[] { AssetRoot }));

            return guids
                .Select(AssetDatabase.GUIDToAssetPath)
                .Distinct(StringComparer.Ordinal)
                .Where(IsSupportedPath)
                .Select(path => new ResourceEntry(GetResourceKind(path), path, CreateIdentifier(path)))
                .OrderBy(entry => entry.Kind)
                .ThenBy(entry => entry.Path, StringComparer.Ordinal)
                .ToList();
        }

        /// <summary>
        /// 判断资源路径是否为 UXML 或 USS 文件。
        /// </summary>
        /// <param name="path">Unity 工程相对路径。</param>
        /// <returns>路径是否为支持的资源类型。</returns>
        private static bool IsSupportedPath(string path)
        {
            return path.EndsWith(".uxml", StringComparison.OrdinalIgnoreCase)
                   || path.EndsWith(".uss", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// 根据资源路径确定生成到哪个常量分组。
        /// </summary>
        /// <param name="path">Unity 工程相对路径。</param>
        /// <returns>资源类型。</returns>
        private static ResourceKind GetResourceKind(string path)
        {
            return path.EndsWith(".uxml", StringComparison.OrdinalIgnoreCase)
                ? ResourceKind.Uxml
                : ResourceKind.Uss;
        }

        #endregion

        #region 源码生成

        /// <summary>
        /// 构建生成文件内容，并对重复的 C# 标识符追加稳定的路径哈希。
        /// </summary>
        /// <param name="entries">资源条目。</param>
        /// <returns>完整的 C# 源码。</returns>
        private static string BuildGeneratedSource(List<ResourceEntry> entries)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// Generated by UxmlUssPathGenerator. Do not edit manually.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("namespace WS_Modules.UIModule.Editor");
            builder.AppendLine("{");
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// Assets 中 UXML 与 USS 资源的 Unity 工程相对路径常量。");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine("    public static class UxmlUssPathConstants");
            builder.AppendLine("    {");
            AppendGroup(builder, entries.Where(entry => entry.Kind == ResourceKind.Uxml), "Uxml");
            AppendGroup(builder, entries.Where(entry => entry.Kind == ResourceKind.Uss), "Uss");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        /// <summary>
        /// 将同一扩展名的资源写入一个嵌套常量类。
        /// </summary>
        /// <param name="builder">源码构建器。</param>
        /// <param name="entries">资源条目。</param>
        /// <param name="groupName">嵌套类名称。</param>
        private static void AppendGroup(StringBuilder builder, IEnumerable<ResourceEntry> entries, string groupName)
        {
            builder.AppendLine($"        /// <summary>所有 {groupName} 资源路径。</summary>");
            builder.AppendLine($"        public static class {groupName}");
            builder.AppendLine("        {");

            var usedNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (ResourceEntry entry in entries)
            {
                string identifier = entry.Identifier;
                if (!usedNames.Add(identifier))
                {
                    identifier = $"{identifier}_{GetStableHash(entry.Path):X8}";
                }

                builder.AppendLine($"            /// <summary>资源路径：{entry.Path}</summary>");
                builder.AppendLine($"            public const string {identifier} = \"{EscapeString(entry.Path)}\";");
            }

            builder.AppendLine("        }");
        }

        /// <summary>
        /// 将资源路径转换为合法的 PascalCase C# 标识符。
        /// </summary>
        /// <param name="path">Unity 工程相对路径。</param>
        /// <returns>常量名称。</returns>
        private static string CreateIdentifier(string path)
        {
            string withoutExtension = Path.ChangeExtension(path, null).Replace('\\', '/');
            var builder = new StringBuilder();
            bool upperNext = true;

            foreach (char character in withoutExtension)
            {
                if (!char.IsLetterOrDigit(character))
                {
                    upperNext = true;
                    continue;
                }

                builder.Append(upperNext ? char.ToUpperInvariant(character) : character);
                upperNext = false;
            }

            if (builder.Length == 0)
            {
                builder.Append("Resource");
            }

            if (char.IsDigit(builder[0]))
            {
                builder.Insert(0, '_');
            }

            return builder.ToString();
        }

        /// <summary>
        /// 计算资源路径的稳定哈希，用于解决常量名称冲突。
        /// </summary>
        /// <param name="value">资源路径。</param>
        /// <returns>稳定的无符号哈希值。</returns>
        private static uint GetStableHash(string value)
        {
            unchecked
            {
                uint hash = 2166136261;
                foreach (char character in value)
                {
                    hash ^= character;
                    hash *= 16777619;
                }

                return hash;
            }
        }

        /// <summary>
        /// 转义 C# 字符串字面量中的特殊字符。
        /// </summary>
        /// <param name="value">待转义文本。</param>
        /// <returns>可写入源码的字符串。</returns>
        private static string EscapeString(string value)
        {
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        #endregion

        #region 嵌套类型

        /// <summary>
        /// 表示一个待生成路径常量的资源。
        /// </summary>
        private sealed class ResourceEntry
        {
            /// <summary>
            /// 初始化资源条目。
            /// </summary>
            /// <param name="kind">资源类型。</param>
            /// <param name="path">Unity 工程相对路径。</param>
            /// <param name="identifier">生成的常量名称。</param>
            public ResourceEntry(ResourceKind kind, string path, string identifier)
            {
                Kind = kind;
                Path = path;
                Identifier = identifier;
            }

            /// <summary>资源类型。</summary>
            public ResourceKind Kind { get; }

            /// <summary>Unity 工程相对路径。</summary>
            public string Path { get; }

            /// <summary>生成的 C# 常量名称。</summary>
            public string Identifier { get; }
        }

        /// <summary>
        /// UXML 和 USS 资源类型。
        /// </summary>
        private enum ResourceKind
        {
            /// <summary>UXML 资源。</summary>
            Uxml,

            /// <summary>USS 资源。</summary>
            Uss,
        }

        #endregion
    }
}
