// <auto-generated>
// Generated by UxmlUssPathGenerator. Do not edit manually.
// </auto-generated>

namespace WS_Modules.UIModule.Editor
{
    /// <summary>
    /// Assets 中 UXML 与 USS 资源的 Unity 工程相对路径常量。
    /// </summary>
    public static class UxmlUssPathConstants
    {
        /// <summary>所有 Uxml 资源路径。</summary>
        public static class Uxml
        {
            /// <summary>资源路径：Assets/GAS_Light/AbilitySystem/Editor/Style/GameplayAbilityAssetRow.uxml</summary>
            public const string AssetsGASLightAbilitySystemEditorStyleGameplayAbilityAssetRow = "Assets/GAS_Light/AbilitySystem/Editor/Style/GameplayAbilityAssetRow.uxml";
            /// <summary>资源路径：Assets/GAS_Light/AbilitySystem/Editor/Style/GameplayAbilityEditor.uxml</summary>
            public const string AssetsGASLightAbilitySystemEditorStyleGameplayAbilityEditor = "Assets/GAS_Light/AbilitySystem/Editor/Style/GameplayAbilityEditor.uxml";
            /// <summary>资源路径：Assets/GAS_Light/AttributeSystem/Editor/Style/GameplayAttributeDefinitionRow.uxml</summary>
            public const string AssetsGASLightAttributeSystemEditorStyleGameplayAttributeDefinitionRow = "Assets/GAS_Light/AttributeSystem/Editor/Style/GameplayAttributeDefinitionRow.uxml";
            /// <summary>资源路径：Assets/GAS_Light/AttributeSystem/Editor/Style/GameplayAttributeEditor.uxml</summary>
            public const string AssetsGASLightAttributeSystemEditorStyleGameplayAttributeEditor = "Assets/GAS_Light/AttributeSystem/Editor/Style/GameplayAttributeEditor.uxml";
            /// <summary>资源路径：Assets/GAS_Light/AttributeSystem/Editor/Style/GameplayAttributeSpecRow.uxml</summary>
            public const string AssetsGASLightAttributeSystemEditorStyleGameplayAttributeSpecRow = "Assets/GAS_Light/AttributeSystem/Editor/Style/GameplayAttributeSpecRow.uxml";
            /// <summary>资源路径：Assets/GAS_Light/Editor/Style/GASSettingWindow.uxml</summary>
            public const string AssetsGASLightEditorStyleGASSettingWindow = "Assets/GAS_Light/Editor/Style/GASSettingWindow.uxml";
            /// <summary>资源路径：Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectAssetRow.uxml</summary>
            public const string AssetsGASLightGameEffectSystemEditorStyleGameplayEffectAssetRow = "Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectAssetRow.uxml";
            /// <summary>资源路径：Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectDetails.uxml</summary>
            public const string AssetsGASLightGameEffectSystemEditorStyleGameplayEffectDetails = "Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectDetails.uxml";
            /// <summary>资源路径：Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectEditor.uxml</summary>
            public const string AssetsGASLightGameEffectSystemEditorStyleGameplayEffectEditor = "Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectEditor.uxml";
            /// <summary>资源路径：Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectModifierRow.uxml</summary>
            public const string AssetsGASLightGameEffectSystemEditorStyleGameplayEffectModifierRow = "Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectModifierRow.uxml";
            /// <summary>资源路径：Assets/GAS_Light/GameplayCueSystem/Editor/Style/GameplayCueEditor.uxml</summary>
            public const string AssetsGASLightGameplayCueSystemEditorStyleGameplayCueEditor = "Assets/GAS_Light/GameplayCueSystem/Editor/Style/GameplayCueEditor.uxml";
            /// <summary>资源路径：Assets/GAS_Light/GameplayCueSystem/Editor/Style/GameplayCueRow.uxml</summary>
            public const string AssetsGASLightGameplayCueSystemEditorStyleGameplayCueRow = "Assets/GAS_Light/GameplayCueSystem/Editor/Style/GameplayCueRow.uxml";
            /// <summary>资源路径：Assets/GAS_Light/TagSystem/Editor/Style/GameplayTagEditor.uxml</summary>
            public const string AssetsGASLightTagSystemEditorStyleGameplayTagEditor = "Assets/GAS_Light/TagSystem/Editor/Style/GameplayTagEditor.uxml";
            /// <summary>资源路径：Assets/GAS_Light/TagSystem/Editor/Style/GameplayTagTreeRow.uxml</summary>
            public const string AssetsGASLightTagSystemEditorStyleGameplayTagTreeRow = "Assets/GAS_Light/TagSystem/Editor/Style/GameplayTagTreeRow.uxml";
            /// <summary>资源路径：Assets/Scripts/Character/Editor/Style/CharacterConfigDetails.uxml</summary>
            public const string AssetsScriptsCharacterEditorStyleCharacterConfigDetails = "Assets/Scripts/Character/Editor/Style/CharacterConfigDetails.uxml";
            /// <summary>资源路径：Assets/Scripts/Character/Editor/Style/CharacterConfigEditorWindow.uxml</summary>
            public const string AssetsScriptsCharacterEditorStyleCharacterConfigEditorWindow = "Assets/Scripts/Character/Editor/Style/CharacterConfigEditorWindow.uxml";
            /// <summary>资源路径：Assets/Scripts/Character/Editor/Style/CharacterConfigListRow.uxml</summary>
            public const string AssetsScriptsCharacterEditorStyleCharacterConfigListRow = "Assets/Scripts/Character/Editor/Style/CharacterConfigListRow.uxml";
            /// <summary>资源路径：Assets/Scripts/Character/Editor/Style/CharacterConfigSummary.uxml</summary>
            public const string AssetsScriptsCharacterEditorStyleCharacterConfigSummary = "Assets/Scripts/Character/Editor/Style/CharacterConfigSummary.uxml";
            /// <summary>资源路径：Assets/Scripts/DialogueSystem/Editor/Style/DialogueGraphEditorWindow.uxml</summary>
            public const string AssetsScriptsDialogueSystemEditorStyleDialogueGraphEditorWindow = "Assets/Scripts/DialogueSystem/Editor/Style/DialogueGraphEditorWindow.uxml";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemArtifactDetails.uxml</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemArtifactDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemArtifactDetails.uxml";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemCommonDetails.uxml</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemCommonDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemCommonDetails.uxml";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemConfigEditorWindow.uxml</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemConfigEditorWindow = "Assets/Scripts/ItemSystem/Editor/Style/ItemConfigEditorWindow.uxml";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemDefinitionListRow.uxml</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemDefinitionListRow = "Assets/Scripts/ItemSystem/Editor/Style/ItemDefinitionListRow.uxml";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemDefinitionSummary.uxml</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemDefinitionSummary = "Assets/Scripts/ItemSystem/Editor/Style/ItemDefinitionSummary.uxml";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemDevelopmentDetails.uxml</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemDevelopmentDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemDevelopmentDetails.uxml";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemStackableDetails.uxml</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemStackableDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemStackableDetails.uxml";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemWeaponDetails.uxml</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemWeaponDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemWeaponDetails.uxml";
            /// <summary>资源路径：Assets/Scripts/SaveSystem/Editor/SaveJsonViewerWindow.uxml</summary>
            public const string AssetsScriptsSaveSystemEditorSaveJsonViewerWindow = "Assets/Scripts/SaveSystem/Editor/SaveJsonViewerWindow.uxml";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/EditorWindowStyle/SkillTimelineEditorWindow.uxml</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowEditorWindowStyleSkillTimelineEditorWindow = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/EditorWindowStyle/SkillTimelineEditorWindow.uxml";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Templates/Item/SkillTimelineItem.uxml</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowTemplatesItemSkillTimelineItem = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Templates/Item/SkillTimelineItem.uxml";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Templates/Item/SkillTimelineLaneItemRow.uxml</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowTemplatesItemSkillTimelineLaneItemRow = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Templates/Item/SkillTimelineLaneItemRow.uxml";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Templates/TimelineRow/SkillTimelineLaneBackgroundRow.uxml</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowTemplatesTimelineRowSkillTimelineLaneBackgroundRow = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Templates/TimelineRow/SkillTimelineLaneBackgroundRow.uxml";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Templates/TimelineRow/SkillTimelineTrackHeaderRow.uxml</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowTemplatesTimelineRowSkillTimelineTrackHeaderRow = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Templates/TimelineRow/SkillTimelineTrackHeaderRow.uxml";
            /// <summary>资源路径：Assets/Scripts/WSFrame/Core/EditorExtensions/Editor/TestCenter/TestCenterWindow.uxml</summary>
            public const string AssetsScriptsWSFrameCoreEditorExtensionsEditorTestCenterTestCenterWindow = "Assets/Scripts/WSFrame/Core/EditorExtensions/Editor/TestCenter/TestCenterWindow.uxml";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/ConfigInstallerView/ConfigInstallerPanel.uxml</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowConfigInstallerViewConfigInstallerPanel = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/ConfigInstallerView/ConfigInstallerPanel.uxml";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/Core/FrameSettingUxml.uxml</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowCoreFrameSettingUxml = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/Core/FrameSettingUxml.uxml";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/EventSystemView/EventInfoItem.uxml</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowEventSystemViewEventInfoItem = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/EventSystemView/EventInfoItem.uxml";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/EventSystemView/EventSystemPanel.uxml</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowEventSystemViewEventSystemPanel = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/EventSystemView/EventSystemPanel.uxml";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/PoolSystemView/PoolSystemView.uxml</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowPoolSystemViewPoolSystemView = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/PoolSystemView/PoolSystemView.uxml";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/UISystemView/UISystemView.uxml</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowUISystemViewUISystemView = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/UISystemView/UISystemView.uxml";
            /// <summary>资源路径：Assets/Scripts/WSFrame/Utilities/Editor/Baking/Style/BakedResultViewerWindow.uxml</summary>
            public const string AssetsScriptsWSFrameUtilitiesEditorBakingStyleBakedResultViewerWindow = "Assets/Scripts/WSFrame/Utilities/Editor/Baking/Style/BakedResultViewerWindow.uxml";
        }
        /// <summary>所有 Uss 资源路径。</summary>
        public static class Uss
        {
            /// <summary>资源路径：Assets/GAS_Light/AbilitySystem/Editor/Style/GameplayAbilityEditor.uss</summary>
            public const string AssetsGASLightAbilitySystemEditorStyleGameplayAbilityEditor = "Assets/GAS_Light/AbilitySystem/Editor/Style/GameplayAbilityEditor.uss";
            /// <summary>资源路径：Assets/GAS_Light/AbilitySystemComponent/Editor/Style/GameplayAbilitySystemComponentInspector.uss</summary>
            public const string AssetsGASLightAbilitySystemComponentEditorStyleGameplayAbilitySystemComponentInspector = "Assets/GAS_Light/AbilitySystemComponent/Editor/Style/GameplayAbilitySystemComponentInspector.uss";
            /// <summary>资源路径：Assets/GAS_Light/AttributeSystem/Editor/Style/GameplayAttributeEditor.uss</summary>
            public const string AssetsGASLightAttributeSystemEditorStyleGameplayAttributeEditor = "Assets/GAS_Light/AttributeSystem/Editor/Style/GameplayAttributeEditor.uss";
            /// <summary>资源路径：Assets/GAS_Light/Editor/Style/GASSettingWindow.uss</summary>
            public const string AssetsGASLightEditorStyleGASSettingWindow = "Assets/GAS_Light/Editor/Style/GASSettingWindow.uss";
            /// <summary>资源路径：Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectEditor.uss</summary>
            public const string AssetsGASLightGameEffectSystemEditorStyleGameplayEffectEditor = "Assets/GAS_Light/GameEffectSystem/Editor/Style/GameplayEffectEditor.uss";
            /// <summary>资源路径：Assets/GAS_Light/GameplayCueSystem/Editor/Style/GameplayCueEditor.uss</summary>
            public const string AssetsGASLightGameplayCueSystemEditorStyleGameplayCueEditor = "Assets/GAS_Light/GameplayCueSystem/Editor/Style/GameplayCueEditor.uss";
            /// <summary>资源路径：Assets/GAS_Light/TagSystem/Editor/Style/GameplayTagEditor.uss</summary>
            public const string AssetsGASLightTagSystemEditorStyleGameplayTagEditor = "Assets/GAS_Light/TagSystem/Editor/Style/GameplayTagEditor.uss";
            /// <summary>资源路径：Assets/Scripts/Character/Editor/Style/CharacterConfigDetails.uss</summary>
            public const string AssetsScriptsCharacterEditorStyleCharacterConfigDetails = "Assets/Scripts/Character/Editor/Style/CharacterConfigDetails.uss";
            /// <summary>资源路径：Assets/Scripts/Character/Editor/Style/CharacterConfigEditorWindow.uss</summary>
            public const string AssetsScriptsCharacterEditorStyleCharacterConfigEditorWindow = "Assets/Scripts/Character/Editor/Style/CharacterConfigEditorWindow.uss";
            /// <summary>资源路径：Assets/Scripts/Character/Editor/Style/CharacterConfigListRow.uss</summary>
            public const string AssetsScriptsCharacterEditorStyleCharacterConfigListRow = "Assets/Scripts/Character/Editor/Style/CharacterConfigListRow.uss";
            /// <summary>资源路径：Assets/Scripts/Character/Editor/Style/CharacterConfigSummary.uss</summary>
            public const string AssetsScriptsCharacterEditorStyleCharacterConfigSummary = "Assets/Scripts/Character/Editor/Style/CharacterConfigSummary.uss";
            /// <summary>资源路径：Assets/Scripts/DialogueSystem/Editor/Style/DialogueGraphEditor.uss</summary>
            public const string AssetsScriptsDialogueSystemEditorStyleDialogueGraphEditor = "Assets/Scripts/DialogueSystem/Editor/Style/DialogueGraphEditor.uss";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemArtifactDetails.uss</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemArtifactDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemArtifactDetails.uss";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemCommonDetails.uss</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemCommonDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemCommonDetails.uss";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemConfigEditorWindow.uss</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemConfigEditorWindow = "Assets/Scripts/ItemSystem/Editor/Style/ItemConfigEditorWindow.uss";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemDefinitionListRow.uss</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemDefinitionListRow = "Assets/Scripts/ItemSystem/Editor/Style/ItemDefinitionListRow.uss";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemDefinitionSummary.uss</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemDefinitionSummary = "Assets/Scripts/ItemSystem/Editor/Style/ItemDefinitionSummary.uss";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemDevelopmentDetails.uss</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemDevelopmentDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemDevelopmentDetails.uss";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemStackableDetails.uss</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemStackableDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemStackableDetails.uss";
            /// <summary>资源路径：Assets/Scripts/ItemSystem/Editor/Style/ItemWeaponDetails.uss</summary>
            public const string AssetsScriptsItemSystemEditorStyleItemWeaponDetails = "Assets/Scripts/ItemSystem/Editor/Style/ItemWeaponDetails.uss";
            /// <summary>资源路径：Assets/Scripts/SaveSystem/Editor/SaveJsonViewerWindow.uss</summary>
            public const string AssetsScriptsSaveSystemEditorSaveJsonViewerWindow = "Assets/Scripts/SaveSystem/Editor/SaveJsonViewerWindow.uss";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/EditorWindowStyle/SkillTimelineEditorWindow.uss</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowEditorWindowStyleSkillTimelineEditorWindow = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/EditorWindowStyle/SkillTimelineEditorWindow.uss";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineActionPhaseClipItem.uss</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowStylesSkillTimelineActionPhaseClipItem = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineActionPhaseClipItem.uss";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineAnimationClipItem.uss</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowStylesSkillTimelineAnimationClipItem = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineAnimationClipItem.uss";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineAttackDetectionClipItem.uss</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowStylesSkillTimelineAttackDetectionClipItem = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineAttackDetectionClipItem.uss";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineAudioClipItem.uss</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowStylesSkillTimelineAudioClipItem = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineAudioClipItem.uss";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineCameraModifierClipItem.uss</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowStylesSkillTimelineCameraModifierClipItem = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineCameraModifierClipItem.uss";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineEventMarkerItem.uss</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowStylesSkillTimelineEventMarkerItem = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineEventMarkerItem.uss";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineItemCommon.uss</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowStylesSkillTimelineItemCommon = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineItemCommon.uss";
            /// <summary>资源路径：Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineVfxClipItem.uss</summary>
            public const string AssetsScriptsSkillSystemEditorSkillTimelineEditorWindowStylesSkillTimelineVfxClipItem = "Assets/Scripts/SkillSystem/Editor/SkillTimelineEditorWindow/Styles/SkillTimelineVfxClipItem.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/Core/EditorExtensions/Editor/TestCenter/TestCenterWindow.uss</summary>
            public const string AssetsScriptsWSFrameCoreEditorExtensionsEditorTestCenterTestCenterWindow = "Assets/Scripts/WSFrame/Core/EditorExtensions/Editor/TestCenter/TestCenterWindow.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/ConfigInstallerView/ConfigInstallerPanel.uss</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowConfigInstallerViewConfigInstallerPanel = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/ConfigInstallerView/ConfigInstallerPanel.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/Core/FrameSettingWindow.uss</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowCoreFrameSettingWindow = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/Core/FrameSettingWindow.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/EventSystemView/EventSystemView.uss</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowEventSystemViewEventSystemView = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/EventSystemView/EventSystemView.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/PoolSystemView/PoolSystemView.uss</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowPoolSystemViewPoolSystemView = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/PoolSystemView/PoolSystemView.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/UISystemView/UISystemView.uss</summary>
            public const string AssetsScriptsWSFrameFrameControlEditorFrameSettingWindowUISystemViewUISystemView = "Assets/Scripts/WSFrame/FrameControl/Editor/FrameSettingWindow/UISystemView/UISystemView.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/UIToolkitExtensions/Editor/GeneralLabel.uss</summary>
            public const string AssetsScriptsWSFrameUIToolkitExtensionsEditorGeneralLabel = "Assets/Scripts/WSFrame/UIToolkitExtensions/Editor/GeneralLabel.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/UIToolkitExtensions/Editor/GraphView/WSGraphNode.uss</summary>
            public const string AssetsScriptsWSFrameUIToolkitExtensionsEditorGraphViewWSGraphNode = "Assets/Scripts/WSFrame/UIToolkitExtensions/Editor/GraphView/WSGraphNode.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/Utilities/Editor/Baking/Style/BakedResultViewerWindow.uss</summary>
            public const string AssetsScriptsWSFrameUtilitiesEditorBakingStyleBakedResultViewerWindow = "Assets/Scripts/WSFrame/Utilities/Editor/Baking/Style/BakedResultViewerWindow.uss";
            /// <summary>资源路径：Assets/Scripts/WSFrame/Utilities/Editor/ConfigEditor/Style/ConfigEditorCommon.uss</summary>
            public const string AssetsScriptsWSFrameUtilitiesEditorConfigEditorStyleConfigEditorCommon = "Assets/Scripts/WSFrame/Utilities/Editor/ConfigEditor/Style/ConfigEditorCommon.uss";
        }
    }
}
