using System;
using System.Collections.Generic;
using Sirenix.OdinInspector;
using UnityEngine;

namespace WS_Modules.Pooling
{
    /// <summary>
    /// Global pool prewarm configuration asset.
    /// This class only stores configuration data; prewarm execution is handled by <see cref="GlobalPoolPrewarmProcessor"/>.
    /// </summary>
    [CreateAssetMenu(fileName = "PoolPrewarmConfig", menuName = "WSFrame/PoolPrewarmConfig", order = 0)]
    public class PoolPrewarmConfig : ScriptableObject
    {
        /// <summary>
        /// GameObject pool prewarm entries. The key maps to a resource path or resource identifier.
        /// </summary>
        [LabelText("GameObject Prewarm Items")]
        public List<GameObjectPoolPrewarmItem> gameObjectPrewarmItems = new();

        /// <summary>
        /// Class pool prewarm entries. Class types are identified by generated <see cref="ClassPoolPrewarmId"/> values.
        /// </summary>
        [LabelText("Class Prewarm Items")]
        public List<ClassPoolPrewarmItem> classPrewarmItems = new();
    }

    /// <summary>
    /// Single GameObject pool prewarm entry.
    /// </summary>
    [Serializable]
    public class GameObjectPoolPrewarmItem
    {
        /// <summary>
        /// Whether this entry is enabled.
        /// </summary>
        [LabelText("Enabled")]
        public bool enable = true;

        /// <summary>
        /// Resource load key, for example Cube or TestFolder/Cube1 under Resources.
        /// </summary>
        [LabelText("Resource Key")]
        [Tooltip("Resource load key, for example Cube or TestFolder/Cube1 under Resources.")]
        [WSAddressableKey]
        public string key;

        /// <summary>
        /// Number of objects to create during initialization.
        /// </summary>
        [LabelText("Init Count")]
        public int initCount = 1;

        /// <summary>
        /// Maximum pool capacity. -1 means unlimited capacity.
        /// </summary>
        [LabelText("Max Capacity")]
        [Tooltip("-1 means unlimited capacity.")]
        public int maxCapacity = -1;
    }

    /// <summary>
    /// Single class pool prewarm entry.
    /// Type selection comes from the generated ClassPoolPrewarmRegistry and avoids runtime Type.GetType string lookup.
    /// </summary>
    [Serializable]
    public class ClassPoolPrewarmItem
    {
        /// <summary>
        /// Whether this entry is enabled.
        /// </summary>
        [LabelText("Enabled")]
        public bool enable = true;

        /// <summary>
        /// Stable type ID generated by the editor generator.
        /// </summary>
        [LabelText("Class Type")]

        public ClassPoolPrewarmId classId;

        /// <summary>
        /// Type display name for Inspector use only. It is not used for runtime lookup.
        /// </summary>
        [LabelText("Display Name"), ReadOnly]
        public string displayName;

        /// <summary>
        /// Number of objects to create during initialization.
        /// </summary>
        [LabelText("Init Count")]
        public int initCount = 1;

        /// <summary>
        /// Maximum pool capacity. -1 means unlimited capacity.
        /// </summary>
        [LabelText("Max Capacity")]
        [Tooltip("-1 means unlimited capacity.")]
        public int maxCapacity = -1;

#if UNITY_EDITOR
        /// <summary>
        /// Odin dropdown options. Display names come from the generated registry and saved values are ClassPoolPrewarmId values.
        /// </summary>
        private IEnumerable<ValueDropdownItem<ClassPoolPrewarmId>> GetClassIdDropdown()
        {
            yield return new ValueDropdownItem<ClassPoolPrewarmId>("None", ClassPoolPrewarmId.None);

            foreach (var entry in ClassPoolPrewarmRegistry.Entries)
            {
                yield return new ValueDropdownItem<ClassPoolPrewarmId>(entry.DisplayName, entry.Id);
            }
        }

        /// <summary>
        /// Syncs the Inspector display name so the configured type is visible while collapsed.
        /// </summary>
        private void OnClassIdChanged()
        {
            displayName = ClassPoolPrewarmRegistry.GetDisplayName(classId);
        }
#endif
    }
}
