// <auto-generated>
// 此文件由 WSFrame WindowCode 绑定规则生成；窗口业务逻辑保留在同名主文件。
// </auto-generated>
namespace RPG.InteractionSystem.UI
{
    /// <summary>维护 InteractionOptionWindow 的生成绑定入口。</summary>
    public partial class InteractionOptionWindow
    {
        /// <summary>获取窗口数据组件。</summary>
        public InteractionOptionWindowDataComponent dataCompt;

        /// <summary>绑定窗口数据组件并应用通用窗口配置。</summary>
        private void BindGeneratedComponents()
        {
            dataCompt = GameObject.GetComponent<InteractionOptionWindowDataComponent>();
            FullScreenWindow = dataCompt.IsFullWindow;
            SetDoAnimation(dataCompt.DoAnimation);
            dataCompt.InitComponent(this);
        }
    }
}
